# -*- coding: utf-8 -*-
"""Finance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7z3BQlfWVJH3mhj4qCwaCl1kjLrX8LK
"""

!pip install -U finance-datareader

import FinanceDataReader as fdr
import pandas as pd

df_krx = fdr.StockListing("KRX")
df_krx.to_csv("krx.csv", index=False)

aviation_industry = df_krx.loc[df_krx["Sector"] == "항공 여객 운송업", ["Symbol", "Market", "Name", "Sector","Industry","ListingDate"]]

aviation_industry.to_csv("aviation.csv", index=False)
aviation_industry

symbols =aviation_industry["Symbol"].values
df = fdr.DataReader(symbols[0])
df

